@WebApiHubTest1_HostAddress = https://localhost:7078

GET {{WebApiHubTest1_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{WebApiHubTest1_HostAddress}}/register/
Accept: application/json
Content-Type: application/json
{
"Email":"testuser5",
"Password":"Test@1234"
}
###

POST {{WebApiHubTest1_HostAddress}}/login/
Accept: application/json
Content-Type: application/json
{
"Email":"testuser",
"Password":"Test@1234"
}
###

